export const LISS_ALL= 'LISS_ALL' ;
export const ADD_TASK='ADD_TASK';
export const TOGGLE_FORM='TOGGLE_FORM';
export const CLOSE_FORM='CLOSE_FORM';
export const OPEN_FORM='OPEN_FORM';
export const UPDATE_STATUS='UPDATE_STATUS';
export const DELETE_ITEM='DELETE_ITEM';
export const EDIT_ITEM='EDIT_ITEM';
export const FILTER_TABLE='FILTER_TABLE';
export const SEARCH='SEARCH'